-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 14:28:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vtstudio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vtstudio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vtstudio` DEFAULT CHARACTER SET utf8 ;
USE `vtstudio` ;

-- -----------------------------------------------------
-- Table `vtstudio`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NULL,
  `id_google` VARCHAR(255) NULL,
  `premium` TINYINT NOT NULL DEFAULT 0,
  `foto` VARCHAR(300) NULL,
  `data_verificado` TIMESTAMP NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `id_google_UNIQUE` (`id_google` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`recuperar_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`recuperar_senha` (
  `id` INT NOT NULL,
  `id_user` INT NOT NULL,
  `token` VARCHAR(200) NOT NULL,
  `data_expira` TIMESTAMP NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) ,
  INDEX `chave_usuario_idx` (`id_user` ASC) ,
  CONSTRAINT `chave_recsenha_usuario`
    FOREIGN KEY (`id_user`)
    REFERENCES `vtstudio`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`mesas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_criada` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_dono` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `chave_dono_idx` (`id_dono` ASC) ,
  CONSTRAINT `chave_mesa_dono`
    FOREIGN KEY (`id_dono`)
    REFERENCES `vtstudio`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `vtstudio`.`drive_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`drive_files` (
  `id` CHAR(36) NOT NULL,
  `id_user` INT NOT NULL,
  `google_drive_id` VARCHAR(255) NOT NULL,
  `google_parent_id` VARCHAR(255) NOT NULL DEFAULT 'root',
  `name` VARCHAR(255) NOT NULL,
  `is_folder` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `chave_usuario_idx` (`id_user` ASC) ,
  CONSTRAINT `chave_drivefiles_usuario`
    FOREIGN KEY (`id_user`)
    REFERENCES `vtstudio`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`user_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`user_mesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_mesa` INT NOT NULL,
  `id_arquivo_personagem` CHAR(36) NOT NULL,
  `cargo` ENUM('player', 'gm') NOT NULL DEFAULT 'player',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) ,
  INDEX `chave_mesa_idx` (`id_mesa` ASC) ,
  INDEX `chave_personagem_idx` (`id_arquivo_personagem` ASC) ,
  CONSTRAINT `chave_usermesa_usuario`
    FOREIGN KEY (`id_user`)
    REFERENCES `vtstudio`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `chave_mesa`
    FOREIGN KEY (`id_mesa`)
    REFERENCES `vtstudio`.`mesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chave_personagem`
    FOREIGN KEY (`id_arquivo_personagem`)
    REFERENCES `vtstudio`.`drive_files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`permissoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TINYTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`mesas_ativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`mesas_ativas` (
  `id` INT NOT NULL,
  `id_mesa` INT NOT NULL,
  `codigo` CHAR(6) NOT NULL,
  `data_fechamento` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `chave_mesa_idx` (`id_mesa` ASC) ,
  CONSTRAINT `chave_mesaativa_mesa`
    FOREIGN KEY (`id_mesa`)
    REFERENCES `vtstudio`.`mesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`preferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`preferencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`user_preferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`user_preferencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_preferencia` INT NOT NULL,
  `valor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `chave_usuario_idx` (`id_user` ASC) ,
  INDEX `chave_preferencia_idx` (`id_preferencia` ASC) ,
  CONSTRAINT `chave_userpreferencia_usuario`
    FOREIGN KEY (`id_user`)
    REFERENCES `vtstudio`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `chave_preferencia`
    FOREIGN KEY (`id_preferencia`)
    REFERENCES `vtstudio`.`preferencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`feedbacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`feedbacks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `texto` TEXT NOT NULL,
  `data_envio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `chave_usuario_idx` (`id_user` ASC) ,
  CONSTRAINT `chave_feedbacks_usuario`
    FOREIGN KEY (`id_user`)
    REFERENCES `vtstudio`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`user_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`user_permissao` (
  `id` INT NOT NULL,
  `id_user_mesa` INT NOT NULL,
  `id_permissao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `chave_user_mesa_idx` (`id_user_mesa` ASC) ,
  INDEX `chave_permissao_idx` (`id_permissao` ASC) ,
  CONSTRAINT `chave_user_mesa`
    FOREIGN KEY (`id_user_mesa`)
    REFERENCES `vtstudio`.`user_mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chave_permissao`
    FOREIGN KEY (`id_permissao`)
    REFERENCES `vtstudio`.`permissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vtstudio`.`drive_credenciais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vtstudio`.`drive_credenciais` (
  `id` INT NOT NULL,
  `id_user` INT NOT NULL,
  `refresh_token` TEXT NOT NULL,
  `access_token` TEXT NOT NULL,
  `token_expira` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `chave_usuario_idx` (`id_user` ASC) ,
  CONSTRAINT `chave_drivecredenciais_usuario`
    FOREIGN KEY (`id_user`)
    REFERENCES `vtstudio`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
